# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ad Begone
version: "0.1.0"
slug: ad-begone
description: Automatically detect and remove ads from podcast MP3 files
url: "https://github.com/samanthavbarron/hass-addons/tree/main/ad-begone"
arch:
  - aarch64
  - amd64
init: false
ingress: false
map:
  - media:rw
  - share:rw
options:
  watch_directory: "/media/podcasts"
  openai_api_key: ""
  openai_model: "gpt-4o"
schema:
  watch_directory: str
  openai_api_key: password
  openai_model: str
image: "ghcr.io/samanthavbarron/{arch}-addon-ad-begone"
